### PR TITLE
Module 5

### PR DESCRIPTION
**Pull request by benhylau**

### CODE REVIEW

**Comment by darkdrgn2k** [comment]
Yeh it was a glith in github and didnt put the fill name into the branch name :/

**Comment by darkdrgn2k** [comment]
server.c was already posted but i added the arm binary as well

**Comment by benhylau** [comment]
@darkdrgn2k where does `server.c` come from? Can you cite?

**Comment by darkdrgn2k** [comment]
added comment with source

https://www.ibm.com/developerworks/systems/library/es-nweb/index.html

**Comment by VictorBjelkholm** [comment]
Can't `server.c` just be replaced with running `python -m http.server 9001` (python3) or `python -m SimpleHTTPServer` instead? It's included in most distros by default. Would make it less of a hassle to having to download/upload a file and compile it.

I can't see any license declared for it, so probably it's following "IBM License Agreement"

**Comment by benhylau** [comment]
@VictorBjelkholm These are all we have, so we don't have python:
https://github.com/benhylau/mesh-router-builder/blob/master/src/mesh-orange-images/mesh-orange/mesh-workshop/debian-config/debian.stretch.multistrap
https://github.com/benhylau/mesh-router-builder/blob/master/src/mesh-orange-images/mesh-orange/mesh-workshop/debian-config/packages.txt

It is a little concerning because license is unclear. I assume it is under [IBM Public License](https://en.wikipedia.org/wiki/IBM_Public_License).

Either way, the code belongs to the software build, so it wouldn't be in this repository. @darkdrgn2k now I know its origin I will get the latest version and put into https://github.com/benhylau/mesh-workshop where the after-image configurations are built, along with `bunny.mp4` and other assets, and deal with all the licensing issues there.

**Comment by darkdrgn2k** [comment]
> I will get the latest version 

The code i included was not simply a stock nweb build.  Stock nweb does not support video/audio files (mp3/mpeg etc). It was modified for our purposes.

https://github.com/tomeshnet/p2p-internet-workshop/commit/5b7a571437203265c3b450d6fdd093d33d992efb#diff-933341f5c7343e1822881e9bac652adaL25

**Pull request merged**
